name: nightly-release

on:
  schedule:
    # 11:00 UTC is 03:00 in Pacific standard time (UTC-8), which is well
    # after nightly TensorFlow wheels are released (around 1--2 AM).
    # (cron syntax: minute hour day-of-month month day-of-week)
    - cron: '0 11 * * *'

permissions:
  contents: read
  id-token: write # Needed for PyPI OIDC trusted publishing

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  nightly-release:
    runs-on: ubuntu-22.04
    needs: ci
    if: github.repository == 'Demonstrandum/tensorbored'
    steps:
      - name: Download pip package
        uses: actions/download-artifact@v4
        with:
          pattern: tensorbored-nightly_py*
          # Download all matching artifacts in the same directory (specified by path)
          merge-multiple: true
          path: wheels

      - name: List wheel files
        run: ls -la wheels/

      - name: Publish nightly to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels/
          print-hash: true
